USE [master]
GO

/****** Object:  Database [BDUsuarios]    Script Date: 23/11/2023 8:13:00 a. m. ******/
CREATE DATABASE [BDUsuarios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDUsuarios', FILENAME = N'F:\BD_Todas\MSSQL\Data\BDUsuarios.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BDUsuarios_log', FILENAME = N'F:\BD_Todas\MSSQL\Data\BDUsuarios_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BDUsuarios] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDUsuarios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDUsuarios] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDUsuarios] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDUsuarios] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDUsuarios] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDUsuarios] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDUsuarios] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDUsuarios] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDUsuarios] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDUsuarios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDUsuarios] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDUsuarios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDUsuarios] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDUsuarios] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDUsuarios] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDUsuarios] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDUsuarios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDUsuarios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDUsuarios] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDUsuarios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDUsuarios] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDUsuarios] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDUsuarios] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDUsuarios] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDUsuarios] SET  MULTI_USER 
GO

ALTER DATABASE [BDUsuarios] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDUsuarios] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDUsuarios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDUsuarios] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BDUsuarios] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDUsuarios] SET  READ_WRITE 
GO



